### ISSUE TITLE
where can I find the test json files? 

### ISSUE THREAD

**Issue by jonas7878** [NVIDIA-Merlin/competitions#2]
Hi: thank you for sharing the code- I was trying to run through them and was unable to locate the test dataset (json files):
rec_test_phase_1.json, intention_test_phase_1.json, rec_test_phase_2.json

If this dataset is not publicly available, I wanted to know whether it would be possible to share sample formats for intention_test_phase_1.json, rec_test_phase_2.json.

I was able to download the train sets from the main contest page.

**Comment by rnyak** [comment]
@jonas7878 thanks for your interest. Unfortunately we are not allowed to share the dataset but you should be able to download data from https://www.coveo.com/en/ailabs/sigir-ecom-data-challenge. 

you can also contact Jacopo Tagliabue for questions regarding the dataset.

Hope that helps.

**Comment by gaceladri** [comment]
I was also looking for this. I have opened an issue at the challenge repo. https://github.com/coveooss/SIGIR-ecom-data-challenge/issues/3#issue-1043855543 @jonas7878 did you get the test set?
